name: ratering_gen_zero
description: A new Flutter application.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio:
  http_parser:
  panorama:
  flutter:
    sdk: flutter
  cupertino_icons:
  image:
  camera: ^0.9.0
  wakelock:
  intl:
  http:
  provider:
  path_provider:
  tflite_flutter:
  tflite_flutter_helper:
  flutter_screenutil:
  scidart:
  google_fonts:
  shared_preferences: ^2.0.6
  flutter_unity_widget: ^4.2.1
  firebase_core: ^1.2.1
  firebase_auth: ^1.4.1
  cloud_firestore: ^2.2.2
  firebase_storage:
  image_picker:
  flutter_conditional_rendering:
  loading_indicator:
  flutter_spinkit: ^5.1.0
  speech_to_text:
  avatar_glow: ^2.0.2
  cached_network_image: ^3.2.0
  hexcolor: ^2.0.7
  agora_rtc_engine: ^4.0.1
  permission_handler:
  audioplayers:
  record: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/models/
    - images/
    - assets/chat_data.json
    - assets/voice/call.mp3
    - assets/voice/sent2.wav

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

